application: quotes-x
version: v1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/?.*
  script: main.app

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static


